name: portfolio
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  adaptive_theme: ^3.6.0
  auto_size_text: ^3.0.0
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  cupertino_modal_sheet: ^1.1.0
  dots_indicator: ^3.0.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.11
  flutter_bloc: ^8.1.6
  flutter_linkify: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.2+1
  flutter_modular: ^6.3.4
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  json_annotation: ^4.9.0
  markdown_widget: ^2.3.2+6
  path: ^1.9.0
  path_provider: ^2.1.3
  photo_view: ^0.15.0
  provider: ^6.1.2
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  url_strategy: ^0.2.0
  vox_flex_theme: ^0.0.31
  vox_widgets: ^0.1.28

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - images/eqalink/
    - images/rcg/
    - images/pakmo/
    - images/images/
    - images/bfs/
    - images/compressed/eqalink/
    - images/compressed/rcg/
    - images/compressed/pakmo/
    - images/compressed/images/
    - images/compressed/bfs/
    - images/
    - images/compressed/
